CREATE TABLE records (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type ENUM('rank_battle', 'room_battle', 'tournament') NOT NULL,
    name VARCHAR(255) NULL,
    win INT UNSIGNED NULL,
    lose INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
